### ISSUE TITLE
 Same links in two "source"

### ISSUE THREAD

**Issue by jahlib** [billmei/every-chatgpt-gui#13]
ChatGPT-web | [demo](https://niek.github.io/chatgpt-web/) | [source](https://github.com/cogentapps/chat-with-gpt)
Chat with GPT | [demo](https://www.chatwithgpt.ai/) | [source](https://github.com/cogentapps/chat-with-gpt)

Same links in "source"

**Comment by billmei** [comment]
Thanks, fixed in https://github.com/billmei/every-chatgpt-gui/commit/d8efe659af2a2ecd383a5d56c685c929c13700d8
