### ISSUE TITLE
Android native apps?

### ISSUE THREAD

**Issue by JamesCropcho** [billmei/every-chatgpt-gui#24]
Are there any native Android apps that are ChatGPT UIs? (other than Poe, which you already list—albeit as a web app)

Thanks.

**Comment by billmei** [comment]
Looks like there are [many options in the Play Store](https://play.google.com/store/search?q=gpt&c=apps&hl=en_US&gl=US) but I can't comment on which ones are native or not - feel free to open a PR, though I won't mirror everything in the Play Store as they're already listed in the Play Store directory.
