### ISSUE TITLE
Add a '100% browser based' category?

### ISSUE THREAD

**Issue by flatsiedatsie** [billmei/every-chatgpt-gui#37]
E.g. for https://chat.webllm.ai/

.. and more to come :-)

**Comment by billmei** [comment]
We have a "Web" category already, not sure how this would be different?

**Comment by flatsiedatsie** [comment]
The difference is quite important. Well, to me at least :-)

The current Web category shows projects that can be used by visiting a website. But for inference they are generally reliant on cloud infrastructure, and not privacy friendly.

The 100% browser-based category, on the other hand, would be for projects that..
1. are accessed by visiting a website, and
2. run inference in the browser itself, locally, on your own device. This guarantees privacy. 

It's the best of both worlds really: you don't have to install software, but are still running LLM's completely locally.

It's also a category that's more challenging to develop for, as these projects are more than a pretty shell around an API. Most projects in it would (currently) rely on just three libraries:
- WebLLM
- Wllama
- Transformers.js

My soon to be released project integrates all three.

![sneak](https://github.com/billmei/every-chatgpt-gui/assets/805405/09be5b3e-603b-4ec0-bfd5-e7701dd15216)

I guess you could argue it's a sub-category of Web?

**Comment by billmei** [comment]
Makes sense! If the intent is that inference is run locally, I can add an "Offline" category, but that doesn't appear to be true for https://chat.webllm.ai/ (I just tested and I get an error when disconnected from the network). If you know of any other projects that fall into this category feel free to add them too :)

**Comment by flatsiedatsie** [comment]
That's odd, I think it should work (once the model is downloaded of course).

Other examples are:
- https://secretllama.com/ (based on WebLLM, I think this pushed the WebLLM team to create their own improved demo with chat.webllm.ai)
- https://huggingface.co/spaces/Xenova/experimental-phi3-webgpu (GPU accelerated Phi 3, but by Transformers.js V3 (which is in beta))
- https://huggingface.co/spaces/Xenova/experimental-moondream-webgpu (image-to-text + normal LLM, also GPU accelerated, by Transformers.js V3)
- There is another one that I can't find right now, but when I do I'll share it too.

And some smaller but very cutting-edge demos:
- https://huggingface.co/spaces/Xenova/realtime-whisper-webgpu (real time voice transcription demo, built with Transformers.js V3 (beta)
- https://github.com/xenova/whisper-web/tree/experimental-webgpu (another version of GPU-accelerated whisper, which allows you to upload an audio file, and it will transcribe it for you)
- https://huggingface.co/spaces/Xenova/musicgen-web (fully browser-based version of musicGen, for creating up to 30 seconds music based on a description. This one is also based on Transformers.js, but doesn't use the V3 GPU acceleration yet)

My upcoming project incorporates pretty much all the Transformers.js demos, so it might be 'double' to also list them separately. But I leave that choice to you.
