### ISSUE TITLE
"ChatGPT UI" in Self-Hosted and Web?

### ISSUE THREAD

**Issue by jangaza** [billmei/every-chatgpt-gui#51]
**Web**
- PatrikZero's ChatGPT UI | [demo](https://chat.patrikzudel.me/) | [source](https://github.com/patrikzudel/PatrikZeros-ChatGPT-API-UI)
    - Fork: SmoothGPT | [demo](https://smoothgpt.app/) | [source](https://github.com/agambon/SmoothGPT)

and
**Self-Hosted**
- ChatGPT UI | [source](https://github.com/patrikzudel/PatrikZeros-ChatGPT-API-UI)

shouldn't it be in only one?

**Comment by billmei** [comment]
The fork is sufficiently different from the original that I thought it could be separated, but good catch on the duplication. I'll remove those.

**Comment by billmei** [comment]
Closed in https://github.com/billmei/every-chatgpt-gui/commit/53751191e1b8657019dee01f7b060761950bca6d
